# Generated by Django 4.1.5 on 2023-01-22 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_eadmin'),
        ('eadmin', '0001_initial'),
        ('customer', '0002_alter_purchase_customer_alter_purchase_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='customer',
            field=models.ForeignKey(default='Free', on_delete=django.db.models.deletion.CASCADE, to='common.customer'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(default='Free', on_delete=django.db.models.deletion.CASCADE, to='eadmin.product'),
        ),
    ]
