# Generated by Django 4.1.5 on 2023-01-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
                ('confirm', models.CharField(max_length=20)),
            ],
        ),
    ]
